### ISSUE TITLE
channel read error: LIBSSL2_ERROR_ENCRYPT

### ISSUE THREAD

**Issue by garethgreenaway** [cy384/ssheven#1]
Realize it's still a prototype just wanted to document some behaviors I'm seeing. :)
Noticed that when network access is unavailable or if a machine goes to sleep, the client crashes and the client window is flooded by this error: "channel read error: LIBSSL2_ERROR_ENCRYPT".

**Comment by cy384** [comment]
thanks for the report, I'll add in some more error checking for that

**Comment by cy384** [comment]
did a basic fix, will be in the next release, thanks again
