### ISSUE TITLE
Potential buffer over-read

### ISSUE THREAD

**Issue by jonirons** [cy384/ssheven#13]
I believe the following lines allow for a buffer over-read (however remote the possibility):

https://github.com/cy384/ssheven/blob/d8753b3676a63b8763a5480817eaad5ce28e4735/ssheven.c#L35
https://github.com/cy384/ssheven/blob/d8753b3676a63b8763a5480817eaad5ce28e4735/ssheven.c#L39

The arrays are length `255` rather than `256`; in both cases, I think it's possible for the array to end up being indexed with `[255]`, which over-reads the buffer.

When reading from `ascii_to_control_code`, you might send garbage across the wire:
https://github.com/cy384/ssheven/blob/d8753b3676a63b8763a5480817eaad5ce28e4735/ssheven.c#L576

For `keycode_to_ascii`, the index to the above read might also end up being garbage:
https://github.com/cy384/ssheven/blob/d8753b3676a63b8763a5480817eaad5ce28e4735/ssheven.c#L571

If this looks like a problem, you'll also want to update this loop:

https://github.com/cy384/ssheven/blob/d8753b3676a63b8763a5480817eaad5ce28e4735/ssheven.c#L50

to:

```
	for (uint16_t i = 0; i < 256; i++)
```
I don't know that any Mac keyboard would even have a key code on it equal to `0xff`, nor do I know if the translation to "ASCII" would ever give `0xff`. This latter seems like it could be possible if there is a layout with a `ˇ` key.

**Comment by cy384** [comment]
thanks for the report, and for reading the code closely! should be an easy fix, I'll get to it this evening

**Comment by cy384** [comment]
should be fixed, thanks again
