### ISSUE TITLE
Option+key combinations do not produce anything

### ISSUE THREAD

**Issue by nortti0** [cy384/ssheven#15]
On the Finnish keyboard option is required to access many common characters like |, $, [], etc. I am running ssheven under Mac OS 9 set to Finnish locale, and it appears to me that ssheven is ignoring these key combinations. Unsure if this is covered under "non-US keyboard input may or may not have issues" or not.

**Comment by cy384** [comment]
Thanks for the report, that is definitely a bug.  Do control combos (like ctrl-c, ctrl-d, ctrl-l) work correctly?

**Comment by nortti0** [comment]
They do.

**Comment by cy384** [comment]
I made some changes to the alt/option handling, can you try this version?  ASCII characters should work, but ones like ä and Ö won't (yet).

download from github: [ssheven-fat-alt-option-fix.zip](https://github.com/cy384/ssheven/files/8121557/ssheven-fat-alt-option-fix.zip) or my site: [ssheven-fat-alt-option-fix.bin](http://www.cy384.com/media/bin/ssheven-fat-alt-option-fix.bin)

**Comment by nortti0** [comment]
That version works as expected. Thank you.

**Comment by cy384** [comment]
committed, the fix will be in the next release
