### ISSUE TITLE
period symbol shown in password prompt

### ISSUE THREAD

**Issue by cory5412** [cy384/ssheven#2]
Hello,

Discovered this by accident, but in SSHeven 0.8.0 prerelease, when I am connecting to a machine and enter a password that has a period (".") symbol in it, the period is shown instead of the typical bullet/circle symbol.

I'm running 9.2.2 on a G3, VM is off. I haven't had a chance to test this on my 7.6.1/601 machine or elsewhere yet.

Here is a screenshot with an example password that has a period in the 5th position:
![2020-11-10_ssheven-pw-error](https://user-images.githubusercontent.com/74269105/98730130-179a9400-2359-11eb-9797-b9436435593d.png)

Please let me know if you need anything else on this, and, thank you for your work on this project!

**Comment by cy384** [comment]
thanks for the report, thar's weird.  Does the server still accept the password?

**Comment by cory5412** [comment]
My apologies for the delay. My password didn't originally have a period in it, but I just swapped to a new password that does and it doesn't authenticate, saying the server rejected the username/password.

**Comment by cy384** [comment]
just did a quick fix, there was a somewhat obvious error in the code

should be ok in the next release, I may do a 0.8.1 bugfix release soon (extremely busy with life, 0.9.0 will be a while)
