### ISSUE TITLE
CTRL+C not working with Swedish keyboard locale

### ISSUE THREAD

**Issue by Knezzen** [cy384/ssheven#3]
CTRL+C is not working when in a session.
I tried terminating top with CTRL+C on all the machines I can access remotely without any luck.

**Comment by cy384** [comment]
tentatively fixed as of commit af285b6 (build version 0.8.2), let me know if this helps

**Comment by cy384** [comment]
tentatively fixed again, feel free to test with 0.8.6

**Comment by cy384** [comment]
with the fix for #15 I think this should be all good now
