### ISSUE TITLE
ssheven 0.8.5 locks up on unsuccessful connection

### ISSUE THREAD

**Issue by Jakeysp** [cy384/ssheven#4]
If I attempt to ssh to a host that cannot be resolved (eg. is offline or incorrect hostname) the error "Connecting endpoint... OTConnect(ssh_con.endpoint, &sndCall, nil) failed" appears in the console. The program then immediately locks up and needs to be Force Quit using Cmd + Opt + Esc.

Using on an iMac G3 running Mac OS 9.2.2. Can't screenshot the above error as the system is unresponsive until ssheven is force quit anyway.

I am having no issues as long as the remote host being connected to responds.

**Comment by cy384** [comment]
thanks for the report, I've done a fix that will be in the next release
